### ISSUE TITLE
Length is larger than buffer. Request=1226842144, capacity=262144

### ISSUE THREAD

**Issue by doctorbean** [aboutsip/pkts#124]
Exception in thread "main" java.lang.IllegalArgumentException: Length is larger than buffer. Request=1226842144, capacity=262144
	at io.pkts.buffer.BoundedInputStreamBuffer.internalReadBytes(BoundedInputStreamBuffer.java:171)
	at io.pkts.buffer.BoundedInputStreamBuffer.readBytes(BoundedInputStreamBuffer.java:131)
	at io.pkts.framer.PcapFramer.frame(PcapFramer.java:66)
	at io.pkts.Pcap.loop(Pcap.java:79)
	at io.pkts.examples.streams.StreamsExample001.main(StreamsExample001.java:77)

what can I do ?

**Comment by jonbo372** [comment]
Hi,

Currently, the only thing you can do is either to change the capacity and rebuild the project. I've been meaning to change the way pcaps are read so that you can read an infinite size (in short, read one frame a time and then throw it away once processed and as such, do not allocate a massive buffer for the entire pcap). However, pretty sure I will not get to that anytime soon but pull requests are welcome! :-)

/Jonas
