### ISSUE TITLE
NoSuchMethodError when parsing SUBSCRIBE packet

### ISSUE THREAD

**Issue by thaeger71** [aboutsip/pkts#38]
Hi there,

i've found an issue when parsing a trace which includes the packet which is included in the attached pcap file. It's a SUBSCRIBE. The exception stack trace looked like this:

Exception in thread "main" java.lang.NoSuchMethodError: io.pkts.packet.sip.SipParseException: method <init>(Ljava/lang/String;)V not found
    at io.pkts.packet.sip.header.ViaHeader$Builder.build(ViaHeader.java:500)
    at io.pkts.packet.sip.header.ViaHeader.frame(ViaHeader.java:195)
    at io.pkts.packet.sip.impl.SipParser.lambda$static$17(SipParser.java:220)
    at io.pkts.packet.sip.impl.SipParser$$Lambda$18/1823923917.apply(Unknown Source)
    at io.pkts.packet.sip.header.impl.SipHeaderImpl.ensure(SipHeaderImpl.java:75)
    at io.pkts.packet.sip.impl.SipParser.frame2(SipParser.java:2088)
    at io.pkts.packet.sip.impl.SipParser.frame(SipParser.java:1993)
    at io.pkts.framer.SIPFramer.frame(SIPFramer.java:47)
    at io.pkts.packet.impl.TransportPacketImpl.getNextPacket(TransportPacketImpl.java:233)
    at io.pkts.packet.impl.AbstractPacket.getPacket(AbstractPacket.java:142)
    at io.pkts.packet.impl.AbstractPacket.getPacket(AbstractPacket.java:151)
    at io.pkts.packet.impl.AbstractPacket.getPacket(AbstractPacket.java:151)
    at io.pkts.packet.impl.AbstractPacket.getPacket(AbstractPacket.java:151)
    at io.pkts.packet.impl.AbstractPacket.hasProtocol(AbstractPacket.java:114)
    at com.hdsnetz.sip.Application$1.nextPacket(Application.java:35)
    at io.pkts.Pcap.loop(Pcap.java:83)
    at com.hdsnetz.sip.Application.walk(Application.java:32)
    at com.hdsnetz.sip.Application.main(Application.java:24)

The code I used was this:

private static void walk(){
        try {
            final Pcap pcap = Pcap.openStream("/home/thaeger/src/powerdebug/traces/1-04-0000000844/1-04-0000000844 (2)/2016-05-03_09-25-58/test.pcap");

```
        pcap.loop(new PacketHandler() {
            @Override
            public boolean nextPacket(Packet packet) throws IOException {
                if (packet.hasProtocol(Protocol.SIP)) {
                    //SipPacket p = (SipPacket) packet.getPacket(Protocol.SIP);
                    System.out.println(packet.getArrivalTime());
                }
                return true;
            }
        });
    } catch (FileNotFoundException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }

}
```

Any ideas ?
[test.pcap.zip](https://github.com/aboutsip/pkts/files/248645/test.pcap.zip)

**Comment by jonbo372** [comment]
I hope you solved your issue considering this is a year later!

Anyway, I just tried to load the message and the reason is

```
io.pkts.packet.sip.SipParseException: You must specify a branch parameter
	at io.pkts.packet.sip.header.ViaHeader$Builder.build(ViaHeader.java:516)
	at io.pkts.packet.sip.header.ViaHeader.frame(ViaHeader.java:210)
	at io.pkts.packet.sip.impl.SipParser.lambda$static$17(SipParser.java:227)
	at io.pkts.packet.sip.header.impl.SipHeaderImpl.ensure(SipHeaderImpl.java:75)
	at io.pkts.packet.sip.impl.SipParser.frame2(SipParser.java:2194)
	at io.pkts.packet.sip.impl.SipParser.frame(SipParser.java:2093)
	at io.pkts.packet.sip.SipMessage.frame(SipMessage.java:709)
	at io.pkts.PktsTestBase.loadSipMessage(PktsTestBase.java:73)
	at io.pkts.packet.sip.SipRequestTest.testParseSubscribe(SipRequestTest.java:56)
```

A via header must contain a branch parameter. Closing this issue.

**Comment by jonbo372** [comment]
Actually, I wonder if it was more related to Issue #27 and also what you reported in #50. In either case, #27 has been fixed.
