### ISSUE TITLE
IndexOutOfBoundException when reading dumps bigger than 2 GB

### ISSUE THREAD

**Issue by thaeger71** [aboutsip/pkts#41]
When I open a Pcap file which is bigger than 2GB with Pcap.openstream, and loop through the packages, after a while I get an IndexOutOfboundExecption if the readed has reached 2GB:

java.lang.IndexOutOfBoundsException
	at java.io.SequenceInputStream.read(SequenceInputStream.java:202)
	at io.pkts.buffer.BoundedInputStreamBuffer.readFromStream(BoundedInputStreamBuffer.java:203)
	at io.pkts.buffer.BoundedInputStreamBuffer.internalReadBytes(BoundedInputStreamBuffer.java:139)
	at io.pkts.buffer.BoundedInputStreamBuffer.readBytes(BoundedInputStreamBuffer.java:93)
	at io.pkts.framer.PcapFramer.frame(PcapFramer.java:52)
	at io.pkts.Pcap.loop(Pcap.java:77)
	at com.hdsnetz.sip.Application.parse(Application.java:186)
	at com.hdsnetz.sip.Application.main(Application.java:34)

**Comment by fabioverdi** [comment]
Same for me. Was it solved?
